### ISSUE TITLE
Semantic highlight / Rust support

### ISSUE THREAD

**Issue by marknefedov** [smallreflection/teal-night#1]
Hello, thanks for this great theme! 
Could you possibly add support for [Semantic Highlight](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) or rust language?

Currently inferred types look to dark to read and macros are same color as functions.

```rust
let some_fun = function("val");
let some_mac = macro!("val");
```

I would like to help you, but I have no idea how vscode themes work.

![image](https://user-images.githubusercontent.com/20001291/173189809-adc268a9-70ed-4447-8f51-ef6792b26fee.png)

**Comment by smallreflection** [comment]
Thanks for the tip, I'll check into this! I haven't developed in Rust at all myself so I'll attempt to get this in the next release!
